Add experimental common-shell-lib v0.2.0 feature
try  remove stderror messages em empty variables

diff --git a/lamw_manager/lamw_manager b/lamw_manager/lamw_manager
--- a/lamw_manager/lamw_manager
+++ b/lamw_manager/lamw_manager
@@ -74,9 +74,9 @@ CheckLocalRootLAMW(){
 		LAMW_MANAGER_ENV+=("LOCAL_ROOT_LAMW=$LOCAL_ROOT_LAMW")
 
 	else 
-		declare -p LOCAL_ROOT_LAMW 2>&1 >/dev/null
-		if [ $? = 0 ]; then 
-			echo "${VERMELHO}Fatal error: 	LOCAL_ROOT_LAMW is declared as empty!${NORMAL}"
+		isVariabelDeclared LOCAL_ROOT_LAMW
+		if [ $? = 0 ]; then
+			echo "${VERMELHO}Fatal error: LOCAL_ROOT_LAMW is declared as empty!${NORMAL}"
 			exit 1
 		fi
 	fi 
