Add experimental support  installing in "selected folder"
Add code to recognize LOCAL_ROOT_LAMW to  change ROOT_LAMW instalation

diff --git a/lamw_manager/lamw_manager b/lamw_manager/lamw_manager
--- a/lamw_manager/lamw_manager
+++ b/lamw_manager/lamw_manager
@@ -68,6 +68,20 @@ CheckUseLamw_manager_setup(){
 		LAMW_MANAGER_ENV+=("USE_SETUP=0")
 	fi
 }
+
+CheckLocalRootLAMW(){
+	if [ "$LOCAL_ROOT_LAMW" != "" ]; then
+		LAMW_MANAGER_ENV+=("LOCAL_ROOT_LAMW=$LOCAL_ROOT_LAMW")
+
+	else 
+		declare -p LOCAL_ROOT_LAMW 2>&1 >/dev/null
+		if [ $? = 0 ]; then 
+			echo "${VERMELHO}Fatal error: LOCAL_ROOT_LAMW is declared as empty!${NORMAL}"
+			exit 1
+		fi
+	fi 
+}
+
 RunAsSudo(){
 	CheckUseLamw_manager_setup
 	sudo -i env ${LAMW_MANAGER_ENV[@]} $CALL_BASH "$LAMW_MGR_INSTALL" $*
@@ -127,6 +141,7 @@ main(){
 	CheckFlags USE_PKEXEC "PKEXEC=1"
 	CheckFlags ENTER_TO_EXIT "ENTER=1"
 	CheckUserIsSudo
+	CheckLocalRootLAMW
 	Run $ARGS
 	DelTempFiles
 }
