Prepare a New hierarchy
Move modules to core
Prepare new flags
Remove unnecessary files

diff --git a/lamw_manager/lamw_manager b/lamw_manager/lamw_manager
--- a/lamw_manager/lamw_manager
+++ b/lamw_manager/lamw_manager
@@ -2,6 +2,7 @@
 #!This script is a wraper to lamw-install.sh
 export DEBUG=0
 export ARGS="$*"
+export LAMW_MGR_CORE=""
 if  [  "$(whoami)" = "root" ];then #impede que o script seja executado pelo root 
 
 	echo "Error: this version  of LAMW4Linux was designed  to run without root priveleges" >&2 # >&2 is a file descriptor to /dev/stderror
@@ -17,22 +18,65 @@ if [ $? = 0 ]; then
 fi
 
 echo "$USER" > /tmp/lamw-overrides.conf
-if [ -e $PWD/lamw-install.sh ]; then
+if [ -e $PWD/core/lamw-install.sh ]; then
 	if [ $DEBUG = 1 ]; then
-		sudo -i bash  -x "$PWD/lamw-install.sh" $ARGS
+		sudo -i bash  -x "$PWD/core/lamw-install.sh" $ARGS
 	else
-		sudo -i bash  "$PWD/lamw-install.sh" $*
+		sudo -i bash  "$PWD/core/lamw-install.sh" $*
 	fi
 else
 	export AUX_PATH=$0
 	export AUX_PATH=${AUX_PATH%/lamw_manager*} #expansão de variavel que remove  lamw_manager (do final da string) restando a path
 	if [ $DEBUG = 1 ]; then
-		sudo -i bash  -x "$AUX_PATH/lamw-install.sh" $ARGS
+		sudo -i bash  -x "$AUX_PATH/core/lamw-install.sh" $ARGS
 	else
-		sudo -i bash  "$AUX_PATH/lamw-install.sh" $*
+		sudo -i bash  "$AUX_PATH/core/lamw-install.sh" $*
 	fi
 fi
 
 if [ -e /tmp/lamw-overrides.conf ];then
 	rm /tmp/lamw-overrides.conf
 fi
+
+
+
+# #!/bin/bash
+# #!This script is a wraper to lamw-install.sh
+
+# export DEBUG=0
+# export ARGS="$*"
+
+# if  [  "$(whoami)" = "root" ] #impede que o script seja executado pelo root 
+# then
+# 	echo "Error: this version  of LAMW4Linux was designed  to run without root priveleges" >&2 # >&2 is a file descriptor to /dev/stderror
+# 	echo "Exiting ..."
+# 	exit 1
+# fi
+# echo "$ARGS" | grep DEBUG=1 > /dev/null 
+# if [ $? = 0 ]; then
+# 	export DEBUG=1;
+# 	export ARGS=${ARGS//DEBUG=1/} # remove todas as ocorrencias de DEBUG=1
+# fi
+
+# echo "$USER" > /tmp/lamw-overrides.conf
+# if [ -e $PWD/lamw-install.sh ]; then
+# 	if [ $DEBUG = 1 ]; then  
+# 		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash -x "$PWD/lamw-install.sh" ${ARGS}
+# 	else
+# 		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash "$PWD/lamw-install.sh" $*
+# 	fi
+# else
+# 	export AUX_PATH=$0
+# 	export AUX_PATH=${AUX_PATH%/lamw-manager*} #expansão de variavel que remove  lamw-manager (do final da string) restando a path
+# 	if [ $DEBUG = 1 ]; then
+# 		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY -x bash "$AUX_PATH/lamw-install.sh" ${ARGS}
+# 	else
+# 		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash "$AUX_PATH/lamw-install.sh" $*
+# 	fi
+# fi
+
+# if [ -e /tmp/lamw-overrides.conf ]
+# then
+# 	rm /tmp/lamw-overrides.conf
+# fi
+# echo "press enter to exit ...";read
