check connection of internet before all critical tasks

diff --git a/lamw_manager/lamw_manager b/lamw_manager/lamw_manager
--- a/lamw_manager/lamw_manager
+++ b/lamw_manager/lamw_manager
@@ -269,6 +269,7 @@ main(){
 	CheckUserIsSudo
 	CheckLocalRootLAMW
 	GetInitialStatus
+	testConnectionInternet
 	CheckNeedLazarusProjectDowngradle
 	StopGradleDaemon
 	Run $ARGS
@@ -287,6 +288,25 @@ TrapControlC(){
 	[ "$bg_pid" != "" ] &&  stopProgressBarAsCancel
 	exit 2
 }
+testConnectionInternet(){
+	
+	local sucess_filler="checking your internet connection"
+
+	getFiller
+
+	echo "${sucess_filler^} ..."
+
+	startProgressBar
+	
+	if ! ping google.com -q -c4 &>/dev/null; then
+		echo "${VERMELHO}Error:${NORMAL} check your internet connection"
+		sleep 0.02
+		stopProgressBarAsFail
+		exit 1
+	fi
+	stopAsSuccessProgressBar
+}
+
 helloMessage(){
 
 	LAMW_INSTALL_VERSION=$(
